"""initial schema

Revision ID: c6cde1a087a1
Revises: 
Create Date: 2026-09-02 12:32:11.345231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6cde1a087a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('background_jobs',
    sa.Column('job_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('exception_id', sa.UUID(), nullable=True),
    sa.Column('job_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('companies',
    sa.Column('company_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), server_default='Asia/Ho_Chi_Minh', nullable=False),
    sa.Column('ranking_weights', postgresql.JSONB(astext_type=sa.Text()), server_default='{"cost":0.4,"time":0.3,"sla_risk":0.3}', nullable=False),
    sa.Column('default_depot_address', sa.Text(), nullable=True),
    sa.Column('default_depot_area', sa.Text(), nullable=True),
    sa.Column('default_cost_per_km', sa.Numeric(), server_default='8000', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('geocode_cache',
    sa.Column('cache_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('address_hash', sa.Text(), nullable=False),
    sa.Column('address_raw', sa.Text(), nullable=False),
    sa.Column('coordinates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('distance_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cached_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('cache_id'),
    sa.UniqueConstraint('address_hash')
    )
    op.create_table('llm_usage_logs',
    sa.Column('log_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('exception_id', sa.UUID(), nullable=True),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_version_id', sa.UUID(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('prompt_versions',
    sa.Column('version_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sub_type', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('rule_versions',
    sa.Column('version_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('rule_key', sa.Text(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_table('exception_groups',
    sa.Column('group_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('exception_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.CheckConstraint("mode IN ('independent', 'combined')", name='ck_exception_groups_mode'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('group_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('dispatcher', 'manager')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.Text(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('driver_name', sa.Text(), nullable=False),
    sa.Column('driver_phone', sa.Text(), nullable=False),
    sa.Column('vehicle_type', sa.Text(), nullable=True),
    sa.Column('max_payload_kg', sa.Numeric(), nullable=False),
    sa.Column('cost_per_km', sa.Numeric(), nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_table('schedules',
    sa.Column('schedule_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.Text(), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_label', sa.Text(), nullable=False),
    sa.Column('trip_sequence', sa.Integer(), server_default='1', nullable=False),
    sa.Column('depot_arrival_time', sa.Time(), nullable=True),
    sa.Column('depot_loading_duration_min', sa.Integer(), nullable=True),
    sa.Column('planned_departure_time', sa.Time(), nullable=True),
    sa.Column('depot_address', sa.Text(), nullable=True),
    sa.Column('stops', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_index('uq_schedules_vehicle_trip', 'schedules', ['company_id', 'vehicle_id', 'shift_date', 'shift_label', 'trip_sequence'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('exceptions',
    sa.Column('exception_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('exception_group', sa.Text(), nullable=False),
    sa.Column('sub_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('vehicle_id', sa.Text(), nullable=True),
    sa.Column('area', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['exception_groups.group_id'], ),
    sa.ForeignKeyConstraint(['reported_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.schedule_id'], ),
    sa.PrimaryKeyConstraint('exception_id')
    )
    op.create_table('impact_analysis',
    sa.Column('impact_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exception_id', sa.UUID(), nullable=False),
    sa.Column('affected_stops', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('total_cost_estimate', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.exception_id'], ),
    sa.PrimaryKeyConstraint('impact_id')
    )
    op.create_table('options',
    sa.Column('option_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exception_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('cost_estimate', sa.Numeric(), nullable=True),
    sa.Column('time_estimate_minutes', sa.Integer(), nullable=True),
    sa.Column('sla_risk_remaining', sa.Numeric(), nullable=True),
    sa.Column('llm_explanation', sa.Text(), nullable=True),
    sa.Column('prompt_version_id', sa.UUID(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.exception_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['exception_groups.group_id'], ),
    sa.ForeignKeyConstraint(['prompt_version_id'], ['prompt_versions.version_id'], ),
    sa.PrimaryKeyConstraint('option_id')
    )
    op.create_table('resource_locks',
    sa.Column('lock_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('exception_id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Text(), nullable=False),
    sa.Column('locked_by', sa.UUID(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.exception_id'], ),
    sa.ForeignKeyConstraint(['locked_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('lock_id')
    )
    op.create_table('decisions',
    sa.Column('decision_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('exception_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('selected_option_id', sa.UUID(), nullable=False),
    sa.Column('confirmed_by', sa.UUID(), nullable=False),
    sa.Column('override_note', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.exception_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['exception_groups.group_id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['options.option_id'], ),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_table('outcomes',
    sa.Column('outcome_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('delivered_on_time', sa.Boolean(), nullable=True),
    sa.Column('actual_cost', sa.Numeric(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.decision_id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('outcome_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcomes')
    op.drop_table('decisions')
    op.drop_table('resource_locks')
    op.drop_table('options')
    op.drop_table('impact_analysis')
    op.drop_table('exceptions')
    op.drop_index('uq_schedules_vehicle_trip', table_name='schedules', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('schedules')
    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('exception_groups')
    op.drop_table('rule_versions')
    op.drop_table('prompt_versions')
    op.drop_table('llm_usage_logs')
    op.drop_table('geocode_cache')
    op.drop_table('companies')
    op.drop_table('background_jobs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
